# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu" do
  name "emu"
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu"

  on_macos do
    on_intel do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_amd64.tar.gz"
      sha256 "281c5b4a11293f0ba966e85ac7597329993188d6317cc5072bbba6e4e983c16b"
    end
    on_arm do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_arm64.tar.gz"
      sha256 "71618f7e03456a75b37fe8b16b4ecc9ac9da640d50c0f7bb449ed9a4ed71536b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_amd64.tar.gz"
      sha256 "67a89a1fafae992d0656295805a12e440255f0f1910cab22f8805a34e12f4825"
    end
    on_arm do
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_arm64.tar.gz"
      sha256 "9362ac1b5f10bc602057bce6bd0f3d5f5f0011803b66ba06aa7d9aca414cf9e9"
    end
  end

  postflight do
    # completions
    generate_completions_from_executable(bin/"emu", "completion")
    # manpages
    man_content = `./emu docs --format man-with-section`
    File.write("emu.1", man_content)
    man1.install "emu.1"
  end

  # No zap stanza required
end
