# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "ec22e1714ca3b7b0fc100c5306e11e0aeb3c1e712b5c1fd9677eb5d530ead396"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "401a983ebe6d6cc5cc9d2f94c8951055aee4b26f522a9dbd3f3e79b34a95820b"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1d84085c6886fc2d33496e3b0382dd09f1fd79e413a30a9bcce1ba20b7cd8b9"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29a63cc27afc566082047cc2f6cccd77921a07d37d6d5ca12534d9e2d0e3c0b7"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "emu"
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu"
  manpage "manpages/emu.1.gz"

  generate_completions_from_executable "emu", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
