# This file was generated by GoReleaser. DO NOT EDIT.
cask "emu" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "878ab7858d9d5d6a24f3908f4cc0cd8f79d30a91fb0ca63c49fa94dc66e889df"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_amd64.tar.gz"
      rename "emu_0.3.4_darwin_amd64/emu", "emu"
    end
    on_arm do
      sha256 "ae66123b2aeee9806fec3901f1e7f4853bd8dcd05219a77517aa0f0fa84d7e8b"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_darwin_arm64.tar.gz"
      rename "emu_0.3.4_darwin_arm64/emu", "emu"
    end
  end

  on_linux do
    on_intel do
      sha256 "e479dc5bc2912f48d7aaa29805f6c70784c7b18a6df456d6f01e78ea1ef43997"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_amd64.tar.gz"
      rename "emu_0.3.4_linux_amd64/emu", "emu"
    end
    on_arm do
      sha256 "87023a6c1b15ec170ca8c3f4a546732a150c75dad765882d50872853d139dbff"
      url "https://github.com/bartekpacia/emu/releases/download/v#{version}/emu_#{version}_linux_arm64.tar.gz"
      rename "emu_0.3.4_linux_arm64/emu", "emu"
    end
  end

  name "emu"
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emu"

  postflight do
    # completions
    generate_completions_from_executable(bin/"emu", "completion")
    # manpages
    man_content = `./emu docs --format man-with-section`
    File.write("emu.1", man_content)
    man1.install "emu.1"
  end

  # No zap stanza required

end
