# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatabaseTools < Formula
  desc "Tools to manage tourist database"
  homepage "https://github.com/opentouristics/database-tools"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opentouristics/database-tools/releases/download/v1.0.1/database-tools_1.0.1_darwin_arm64.tar.gz"
      sha256 "f6bcbdf26a3206a42f792b5bbdd4a086a294326dd713a471b90702b3d68e11fb"

      def install
        bin.install "touristdb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opentouristics/database-tools/releases/download/v1.0.1/database-tools_1.0.1_darwin_amd64.tar.gz"
      sha256 "adc74836f2bb4bef1d7b56b1268b23ab272ac9f76e6efe6404b3faa1b7f94f77"

      def install
        bin.install "touristdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/opentouristics/database-tools/releases/download/v1.0.1/database-tools_1.0.1_linux_amd64.tar.gz"
      sha256 "7772fc361be25120f8438b8874af34ada3ca5a445c301f397f51bb69bd8d469a"

      def install
        bin.install "touristdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opentouristics/database-tools/releases/download/v1.0.1/database-tools_1.0.1_linux_arm64.tar.gz"
      sha256 "5335184f3cef0ac44cb5df6176a0997d92ca0226d2bc97cef514df79d02da302"

      def install
        bin.install "touristdb"
      end
    end
  end
end
