# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emu < Formula
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_darwin_arm64.tar.gz"
      sha256 "af7ac56a02213baf914d636b260205f6eaeca3c96ef1ec0fff71ca4465a80f7e"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_darwin_amd64.tar.gz"
      sha256 "70cc688171c7e2d3c569cdc4afb9c595ef52032f32a4779d4ba2b473046d5339"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_linux_arm64.tar.gz"
      sha256 "4cceadaea083f440c7e9e7fabe08127b2464c68505721c2182bf534b68c4aaf1"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_linux_amd64.tar.gz"
      sha256 "70ed88a45a9a8f4eead9e53805c780efa50b845bd6d1a875b8dc623ab76f8a61"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
  end
end
