# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emu < Formula
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_darwin_amd64.tar.gz"
      sha256 "bfa4fef00af1b99b90a7f3c68feefdf06846fa0338f76fd384b8ba79d3576d8f"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_darwin_arm64.tar.gz"
      sha256 "182c76248dc3fe87ae3cbcab203b29db45a3b67cd3951352049db10b3a95134c"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_linux_amd64.tar.gz"
      sha256 "c05802eccf6c9425cf362a866db56e89e7a47982b6d62b2cf4c82a3f0b290a70"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/emu/releases/download/v0.2.5/emu_0.2.5_linux_arm64.tar.gz"
      sha256 "bcf394ab4f60cb94ffb0da36009258406d8740743d2cb4a119482454c4a21550"

      def install
        bin.install "emu"
        bash_completion.install "autocomplete/bash_autocomplete" => "emu"
        zsh_completion.install "autocomplete/zsh_autocomplete" => "_emu"
      end
    end
  end
end
