# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emu < Formula
  desc "Handy mini-CLI for more pleasant work with Android Emulator"
  homepage "https://github.com/bartekpacia/emu"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/emu/releases/download/v0.3.0/emu_0.3.0_darwin_amd64.tar.gz"
      sha256 "f996dfb014afa50230d0cb8765c4021b34ce8bac49976bd1fe6dc4fd1eb7a692"

      def install
        man_content = `./emu docs --format man-with-section`
        File.write("emu.1", man_content)

        bin.install "emu"
        generate_completions_from_executable(bin/"emu", "completion")

        man1.install "emu.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/emu/releases/download/v0.3.0/emu_0.3.0_darwin_arm64.tar.gz"
      sha256 "bf7110ee0fb9a3eb75fd098b1e7a4a3d45a63860edc1113da50576759f52208b"

      def install
        man_content = `./emu docs --format man-with-section`
        File.write("emu.1", man_content)

        bin.install "emu"
        generate_completions_from_executable(bin/"emu", "completion")

        man1.install "emu.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartekpacia/emu/releases/download/v0.3.0/emu_0.3.0_linux_amd64.tar.gz"
        sha256 "6cd53b1cb76ac41a35410e83ce2e42d0293c614305da16b85ffb8eb143680135"

        def install
          man_content = `./emu docs --format man-with-section`
          File.write("emu.1", man_content)

          bin.install "emu"
          generate_completions_from_executable(bin/"emu", "completion")

          man1.install "emu.1"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartekpacia/emu/releases/download/v0.3.0/emu_0.3.0_linux_arm64.tar.gz"
        sha256 "ca6233ff453cad901c1664f34e364233194e202587fb29dbfcf7de4f7a69736e"

        def install
          man_content = `./emu docs --format man-with-section`
          File.write("emu.1", man_content)

          bin.install "emu"
          generate_completions_from_executable(bin/"emu", "completion")

          man1.install "emu.1"
        end
      end
    end
  end
end
