# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fh < Formula
  desc "CLI app talking to F&Home API – a smart home system"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.5/fhome_0.0.5_darwin_amd64.tar.gz"
      sha256 "10a4084e444ba1c3e6070dd5de1b52adc1847462d0f96d5f6531d6a879f0a3fa"

      def install
        bin.install "fh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.5/fhome_0.0.5_darwin_arm64.tar.gz"
      sha256 "e0ced9f52544caa7dc57387c27d653109081317a8b149a81826731d1318c192d"

      def install
        bin.install "fh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.5/fhome_0.0.5_linux_arm64.tar.gz"
      sha256 "61b5c8a92af8d1a036d195c1540e028a7fbaf5fdf35608840f03da4b9d7eefb1"

      def install
        bin.install "fh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.5/fhome_0.0.5_linux_amd64.tar.gz"
      sha256 "b81e081cad84e08115065851c98f2e468ddeb95d96f73ead81cd4b59ef88c8b7"

      def install
        bin.install "fh"
      end
    end
  end
end
