# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fh < Formula
  desc "CLI app talking to F&Home API – a smart home system"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.6/fhome_0.0.6_darwin_amd64.tar.gz"
      sha256 "8b50e9f250e93eef9a265e539e6b8134bfa4888fa2922cab668aefbbd3805435"

      def install
        bin.install "fh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.6/fhome_0.0.6_darwin_arm64.tar.gz"
      sha256 "2a87683716c71cb6a5e3d4e5167f1622834be199335436d2d1f5d34c68ab5915"

      def install
        bin.install "fh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.6/fhome_0.0.6_linux_amd64.tar.gz"
      sha256 "9fa203ad2132b27e6c1225b1fbc3f714fee66ef9fa2fa3fc2f4a90d559b51781"

      def install
        bin.install "fh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.0.6/fhome_0.0.6_linux_arm64.tar.gz"
      sha256 "012e8ca30a550ce393564a2859f25346162d8b81d6396b4d08c13ddb390a9f35"

      def install
        bin.install "fh"
      end
    end
  end
end
