# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fhomed < Formula
  desc "Background daemon for F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.20/fhomed_0.1.20_darwin_arm64.tar.gz"
      sha256 "7c25dbf97a08897bbdaa58c0263415f1795511935951b1e735f3ab8df4bd03ef"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.20/fhomed_0.1.20_darwin_amd64.tar.gz"
      sha256 "6bf882e06e296cb7b1f3a89b2bb44ed8cbd1f36f6016d5f7f3ff22d48838e581"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.20/fhomed_0.1.20_linux_arm64.tar.gz"
      sha256 "9b70fe17aec7162a94db25ffcac0e7e2b142ad7a3d6970e46e4d5f323f5e5c58"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.20/fhomed_0.1.20_linux_amd64.tar.gz"
      sha256 "4680106c4b82bde48c9070cbeab1818f207b3f711e2b5ba00945e140d9f1d0c4"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
  end
end
