# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FhomeExporter < Formula
  desc "Prometheus exporter for F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-exporter_0.3.5_darwin_amd64.tar.gz"
      sha256 "d2d07db124bd7e0f7c090d491fa362ad6d795bad883de8905713155c842b4002"

      define_method(:install) do
        bin.install "fhome-exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-exporter_0.3.5_darwin_arm64.tar.gz"
      sha256 "5b1b1266e3ee9e06a107db54670d4822ec39cd1998e8c6de0fb2de2061da7933"

      define_method(:install) do
        bin.install "fhome-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-exporter_0.3.5_linux_amd64.tar.gz"
      sha256 "94fd9ba1e97cc9fabe8cc125a7d768d1359061b0f550f92b9edf428fe302b679"
      define_method(:install) do
        bin.install "fhome-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-exporter_0.3.5_linux_arm64.tar.gz"
      sha256 "e8f3bed55c1dabcd40e76b92909a449793f0908648479c582c9b856f5639f850"
      define_method(:install) do
        bin.install "fhome-exporter"
      end
    end
  end
end
