# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FhomeHomekit < Formula
  desc "HomeKit bridge for F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-homekit_0.3.5_darwin_amd64.tar.gz"
      sha256 "ddb6304d3cc9f92bb224e7e160baabc368ac77a68836dc4275638b9dd05bdf7c"

      define_method(:install) do
        bin.install "fhome-homekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-homekit_0.3.5_darwin_arm64.tar.gz"
      sha256 "44b360b8c5442370f3d87e723b2a9ed0e1d4440daf9a604a780f290a9568db59"

      define_method(:install) do
        bin.install "fhome-homekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-homekit_0.3.5_linux_amd64.tar.gz"
      sha256 "59d46eefdd8e98ce5512ccda9635ca7ea4b86fa5c584f6ac2ad1367e18f8c42f"
      define_method(:install) do
        bin.install "fhome-homekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.3.5/fhome-homekit_0.3.5_linux_arm64.tar.gz"
      sha256 "1f1d169bb109a8259958aff624c8263cb649a6fd20b1cede59f2c34f2991bff2"
      define_method(:install) do
        bin.install "fhome-homekit"
      end
    end
  end
end
