# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fhomed < Formula
  desc "Background daemon for F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.18/fhomed_0.1.18_darwin_amd64.tar.gz"
      sha256 "a4359aa7b5f1dd777c5059e0efcce436805fc8111ce700ffbb5933a05cc25804"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.18/fhomed_0.1.18_darwin_arm64.tar.gz"
      sha256 "d5dbe08d2778575d1c69b6afdafbd3e4ac0432457ac5f1dc1dd04a62e56aec78"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.18/fhomed_0.1.18_linux_arm64.tar.gz"
      sha256 "fe923245215380c2ae1d3ac22325da7aafb662537c557cb2bbc412811d2c9f43"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.18/fhomed_0.1.18_linux_amd64.tar.gz"
      sha256 "2523c40ad1bf91c32d652ca1aed2125017beb1ae02571818be3d2934c1d72bde"

      def install
        bin.install "fhomed"
        bash_completion.install "autocomplete/bash_autocomplete_fhomed" => "fhomed"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhomed" => "_fhomed"
      end
    end
  end
end
