# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fhomed < Formula
  desc "Background daemon for F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.2/fhomed_0.1.2_darwin_amd64.tar.gz"
      sha256 "530fe93a0a632bbfb307a4c78ea3c1ea4bcc4f4c09660014c63d8ceb3f6ef46f"

      def install
        bin.install "fhomed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.2/fhomed_0.1.2_darwin_arm64.tar.gz"
      sha256 "4b2c5ebaf8857ea59d3497b1ca656b367c379c01beddd34d71dccbbdc4010634"

      def install
        bin.install "fhomed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.2/fhomed_0.1.2_linux_arm64.tar.gz"
      sha256 "499743cd26acce5b5d76c1b42140ffa3be4193ca942c685306bff7846bf91571"

      def install
        bin.install "fhomed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/fhome/releases/download/v0.1.2/fhomed_0.1.2_linux_amd64.tar.gz"
      sha256 "14d3c3b3f89bfab7965540a1758f1cb5608596ccdceca40b659464c75b1032ea"

      def install
        bin.install "fhomed"
      end
    end
  end
end
