# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fhome < Formula
  desc "Interact with smart home devices connected to F&Home"
  homepage "https://github.com/bartekpacia/fhome"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bartekpacia/fhome/releases/download/v0.2.3/fhome_0.2.3_darwin_amd64.tar.gz"
      sha256 "d30238ddb87e12ef1fe6b783ace446e8cbc448392a92e6081826e65ef98b26a9"

      def install
        bin.install "fhome"
        bash_completion.install "autocomplete/bash_autocomplete_fhome" => "fhome"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"
      end
    end
    on_arm do
      url "https://github.com/bartekpacia/fhome/releases/download/v0.2.3/fhome_0.2.3_darwin_arm64.tar.gz"
      sha256 "2da4d6429538092712a5d6fcbed5d2eaeadd11deed4e9bb7be7fb8181990edc0"

      def install
        bin.install "fhome"
        bash_completion.install "autocomplete/bash_autocomplete_fhome" => "fhome"
        zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartekpacia/fhome/releases/download/v0.2.3/fhome_0.2.3_linux_amd64.tar.gz"
        sha256 "d9ea2d6be0326dc6bf3f2aede0ca448d8cd6e50d41914eb8a3c11244040d4ad4"

        def install
          bin.install "fhome"
          bash_completion.install "autocomplete/bash_autocomplete_fhome" => "fhome"
          zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bartekpacia/fhome/releases/download/v0.2.3/fhome_0.2.3_linux_arm64.tar.gz"
        sha256 "17b2914a11f31396789b03c0150aeb84663c412a84ddc41487accb7e886166bb"

        def install
          bin.install "fhome"
          bash_completion.install "autocomplete/bash_autocomplete_fhome" => "fhome"
          zsh_completion.install "autocomplete/zsh_autocomplete_fhome" => "_fhome"
        end
      end
    end
  end
end
