# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramFhomeBot < Formula
  desc "Telegram bot for interacting with F&Home smart home devices"
  homepage "https://github.com/bartekpacia/telegram-fhome-bot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bartekpacia/telegram-fhome-bot/releases/download/v0.1.0/telegram-fhome-bot_0.1.0_darwin_amd64.tar.gz"
      sha256 "228b640103681ac3bd062059d75238b1e18bcc7de4cbad4bfa8e3555e2074f9f"

      def install
        bin.install "telegram-fhome-bot"
        generate_completions_from_executable(bin/"telegram-fhome-bot", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bartekpacia/telegram-fhome-bot/releases/download/v0.1.0/telegram-fhome-bot_0.1.0_darwin_arm64.tar.gz"
      sha256 "afe54e9ae9d372f7054cd3efe178e39b1a80e16e6253b098bd7193080e3a37fb"

      def install
        bin.install "telegram-fhome-bot"
        generate_completions_from_executable(bin/"telegram-fhome-bot", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/telegram-fhome-bot/releases/download/v0.1.0/telegram-fhome-bot_0.1.0_linux_amd64.tar.gz"
      sha256 "bc08d9ba01a26afd0870b012c0f2d8c4b616d222ee3c444b5d19c67ec901de77"
      def install
        bin.install "telegram-fhome-bot"
        generate_completions_from_executable(bin/"telegram-fhome-bot", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bartekpacia/telegram-fhome-bot/releases/download/v0.1.0/telegram-fhome-bot_0.1.0_linux_arm64.tar.gz"
      sha256 "cc672c6c8895673b6283e0487648279d5cac1626c11347dd5d4a93964921d29c"
      def install
        bin.install "telegram-fhome-bot"
        generate_completions_from_executable(bin/"telegram-fhome-bot", "completion")
      end
    end
  end
end
